version: '3'
services:
  database:
    image: mysql:5.7.25
    restart: always
    container_name: ${DB_DOCKER_NAME}
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 33061:3306
    volumes:
      - mysql: /var/lib/mysql
volumes:
  mysql: