version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.25
    restart: always
    ports:
      - 4466:4466
    depends_on:
      - mysql
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: REPLACE_WITH_MYSQL_ROOT_PASSWORD 
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: REPLACE_WITH_MYSQL_ROOT_PASSWORD
  node:
    image: qiwenzhao/tprs.node:latest
    restart: always
    depends_on:
      - prisma
    ports:
      - 4000:4000
    environment:
      PRISMA_ENDPOINT: "http://prisma:4466"
      PRISMA_SECRET: REPLACE_WITH_PRISMA_SECRET
      JWT_SECRET: REPLACE_WITH_JWT_SECRET
  web:
    image: qiwenzhao/tprs.web:latest
    restart: always
    depends_on:
      - node
    ports:
      - 8888:80